services:
  pdfusion:
    image: ghcr.io/xoudusz/pdfusion:latest
    container_name: pdfusion
    restart: unless-stopped
    network_mode: nginx_proxy_default
    environment:
      - VIRTUAL_HOST=pdf.hyvitech.org
      - LETSENCRYPT_HOST=pdf.hyvitech.org
